export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ALL_QUESTIONSET_REQUEST = "ALL_QUESTIONSET_REQUEST";
export const ALL_QUESTIONSET_SUCCESS = "ALL_QUESTIONSET_SUCCESS";
export const ALL_QUESTIONSET_FAIL = "ALL_QUESTIONSET_FAIL";

export const ALL_QUESTION_REQUEST = "ALL_QUESTION_REQUEST";
export const ALL_QUESTION_SUCCESS = "ALL_QUESTION_SUCCESS";
export const ALL_QUESTION_FAIL = "ALL_QUESTION_FAIL";
